apiVersion: v1
kind: Pod
metadata:
  name: kafka-test-client
spec:
  containers:
  - command:
    - sh
    - -c
    - exec tail -f /dev/null
    image: confluentinc/cp-kafka:4.1.2-2
    imagePullPolicy: IfNotPresent
    name: kafka
    resources: 
      limits:
        cpu: "800m"
        memory: "800Mi"
      requests:
        cpu: "400m"
        memory: "400Mi"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File